api_platform:
    show_webby : false
    # The title of the API.
    title: 'API title'

    # The description of the API.
    description: 'API description'

    # The version of the API.
    version: '0.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: [ 'application/json' ]

        jsonld:
            mime_types: [ 'application/ld+json' ]

        html:
            mime_types: [ 'text/html' ]
